name: st4rtrack
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.12.5
  - pip=24.2
  - pip:
      - torch==2.5.1
      - torchvision==0.20.1
      - torchaudio==2.5.1
      - numpy==2.0.2
      - opencv-python==4.11.0.86
      - matplotlib==3.10.1
      - pillow==11.0.0
      - scipy==1.15.2
      - scikit-image==0.25.2
      - tqdm==4.66.5
      - wandb==0.19.7
      - einops==0.8.1
      - huggingface-hub==0.29.1
      - safetensors==0.5.3
      - gradio==5.20.0
      - trimesh==4.6.4
      - xformers==0.0.24
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - ipython==9.2.0
      - jupyter==1.1.1
      - jupyterlab==4.4.0
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - ffmpeg-python==0.2.0
      - plyfile==1.1
      - pycolmap==3.11.1
      - pyyaml==6.0.2
      - jsonpatch==1.33
      - requests==2.32.3
      - setuptools==73.0.1
      - wheel==0.44.0
      - packaging==24.1
      - viser==1.0.6